### PR TITLE
Permit trec_eval to compile under cygwin

### PR DESCRIPTION
**Pull request by cmacdonald**

### CODE REVIEW

**Comment by isoboroff** [comment]
Yes, this is definitely one we should pull onto the master branch.

**Comment by cmacdonald** [comment]
:-)

Interestingly, I compiled for 32bit Cygwin, and Windows Defender on a different machine suggests it is a virus. I have submitted the "offending" trec_eval.exe to Microsoft, so hopefully this is not a long-term problem.

**Comment by isoboroff** [comment]
Sorry I let this one sit so long for what was an obvious merge, but a filed issue on Windows compilation spurred me to it.  Craig, do you have time to jot me a up a quick README.windows file?

**Comment by cmacdonald** [comment]
@isoboroff you closed the pull request, but did you actually commit it to any branch?

**Pull request merged**
