### PR TITLE
bump checkout action version to prevent warnings

### PR DESCRIPTION
**Pull request by cmacdonald**

### CODE REVIEW

**Comment by cmacdonald** [comment]
Test is failing:

```
< iprec_at_recall_0.30  	all	0.2852
---
> iprec_at_recall_0.30  	all	0.2732
```

**Comment by isoboroff** [comment]
Is this on all platforms?  I was talking to Sean and Richard an out fixing the Windows build. I also updated the test ground truth for 10.0 and I wonder if some system issue is happening

**Comment by cmacdonald** [comment]
> Is this on all platforms? 

That failure is on Linux. Not sure if others are affected - it cancels all jobs OS fails.
 
> I was talking to Sean and Richard an out fixing the Windows build.

So I heard. Hence I went back to look at the Github Actions.

You could probably make an Action to build your three binaries.

**Comment by isoboroff** [comment]
Craig, I fixed a bug in m_iprec_at_recall and m_11pt_avg, and now builds for macOS and Ubuntu build.  I don't understand the Windows error... can you take a quick look?

**Comment by cmacdonald** [comment]
Looking at this now.

**Pull request merged**
